#!/bin/bash

curl --header "Content-Type: application/json" \
http://localhost:5000/get_score \
--request POST \
--data "{\"source\":\"The French Revolution 1789-1799 marked the end of a historical era and the beginning of the Contemporary Age, putting into practice the most advanced liberal ideas and applying universal male suffrage for the first time in history. This important event put an end to the system of absolute monarchies and laid the foundations for the political and social organization of the contemporary world. \\nA key figure in the French Revolution was Napoleon Bonaparte, whose role is controversial: some see him as a monster who caused chaos and destruction, while others consider him a military genius who laid the foundations of the revolution and its ideals of freedom , equality and fraternity. Despite the discrepancies, it cannot be denied that Napoleon was influential in the application of revolutionary postulates and in the consolidation of some revolutionary achievements, such as the destruction of feudal structures and the rise of the bourgeoisie as the dominant social class.\", \"note\":\"The French Revolution was a crucial political change in Europe at the end of the 18th century and marked the beginning of Contemporary History. It was not only important for France, but also served as an example for other countries where similar social conflicts broke out, against an anachronistic and oppressive regime, such as the monarchy. This revolution meant the triumph of a poor people, oppressed and tired of injustices, over the privileges of the feudal nobility and the absolutist state.\\nThe causes that unleashed the French Revolution were multiple, including ideological, economic, social and political causes . The main purpose of the revolution was the disintegration of the old order and its institutions, and with it the formation of a new democratic order, based on centralization, egalitarianism and nationalism.\"}"



curl --header "Content-Type: application/json" \
http://localhost:5000/get_score \
--request POST \
--data "{\"source\":\"The French Revolution 1789-1799 marked the end of a historical era and the beginning of the Contemporary Age, putting into practice the most advanced liberal ideas and applying universal male suffrage for the first time in history. This important event put an end to the system of absolute monarchies and laid the foundations for the political and social organization of the contemporary world. \\nA key figure in the French Revolution was Napoleon Bonaparte, whose role is controversial: some see him as a monster who caused chaos and destruction, while others consider him a military genius who laid the foundations of the revolution and its ideals of freedom , equality and fraternity. Despite the discrepancies, it cannot be denied that Napoleon was influential in the application of revolutionary postulates and in the consolidation of some revolutionary achievements, such as the destruction of feudal structures and the rise of the bourgeoisie as the dominant social class.\", \"note\":\"The French Revolution 1789-1799 marked the end of a historical era and the beginning of the Contemporary Age, putting into practice the most advanced liberal ideas and applying universal male suffrage for the first time in history. This important event put an end to the system of absolute monarchies and laid the foundations for the political and social organization of the contemporary world. \\nA key figure in the French Revolution was Napoleon Bonaparte, whose role is controversial: some see him as a monster who caused chaos and destruction, while others consider him a military genius who laid the foundations of the revolution and its ideals of freedom , equality and fraternity. Despite the discrepancies, it cannot be denied that Napoleon was influential in the application of revolutionary postulates and in the consolidation of some revolutionary achievements, such as the destruction of feudal structures and the rise of the bourgeoisie as the dominant social class.\"}"



